import AppLayout from '@/components/layout/AppLayout';
import AIInsightPanel from '@/components/recommendations/AIInsightPanel';
import RecommendationList from '@/components/recommendations/RecommendationList';
import styles from './recommendations.module.scss';

export const metadata = { title: 'AI Recommendations — MarketMind' };

export default function RecommendationsPage() {
  return (
    <AppLayout>
      <div className={styles.page}>
        <header className={styles.header}>
          <h1 className={styles.title}>AI Recommendations</h1>
          <p className={styles.subtitle}>Generated by agentic AI analysis of market signals</p>
        </header>

        <div className={styles.layout}>
          <div className={styles.main}>
            {/* TODO: LOGIC agent — fetch AI recommendation list */}
            <RecommendationList />
          </div>
          <aside className={styles.panel}>
            {/* TODO: LOGIC agent — wire AI insight stream */}
            <AIInsightPanel />
          </aside>
        </div>
      </div>
    </AppLayout>
  );
}
